# Generated by Django 5.1.1 on 2025-04-10 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_aadhar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='other_medical_details',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='hereditary_diseases',
            field=models.CharField(blank=True, default='None', max_length=255),
        ),
    ]
