# Generated by Django 5.1.1 on 2025-04-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_other_medical_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
