# Generated by Django 5.1.1 on 2025-04-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
