# Generated by Django 5.1.1 on 2025-04-08 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseSpecializationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100, unique=True)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='doctor',
            old_name='department',
            new_name='specialization',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_days',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='available_times',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
