# Generated by Django 5.1.1 on 2025-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_appointment_doctoravailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled')], default='booked', max_length=20),
        ),
    ]
