# Generated by Django 5.1.1 on 2025-04-25 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0006_hospital_appointment_age_appointment_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
