# Generated by Django 5.1.1 on 2025-04-26 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0008_appointment_hospital'),
        ('hospital', '0004_remove_booking_category_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospital',
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hospital.hospital'),
        ),
    ]
